#! /usr/bin/env python

import sys, os

dirname = os.path.dirname(os.path.realpath(__file__))
ldpath  = os.path.join(dirname, 'lib')

cmd = 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:%s && %s' % \
        (ldpath, os.path.join(dirname, 'moto-gui'))

os.system(cmd)
