Import('env')
env.SConscript(['libmotoutil/SConscript',
                'libmoto/SConscript',
                'libmotogui/SConscript',
                'libmototest/SConscript'])

env = env.Clone()
env.Append(LIBS=['moto', 'motoutil', 'motogui', 'mototest'], LIBPATH='./lib')
env.Program('$MOTO_GUI', 'moto-gui.c')
