Import('env')
env.SConscript(['libmotoutil/SConscript',
                'libmoto/SConscript',
                'libmotogui/SConscript',
                'libmototest/SConscript'])

env.Program('$MOTO_GUI', 'moto-gui.c',
            LIBS=['moto', 'motoutil', 'motogui', 'mototest'],
            LIBPATH='./lib')

# env.Program('moto', 'moto.c',
#            LIBS=['moto', 'motoutil', 'motogui', 'mototest'],
#            LIBPATH='./lib')
